name: Validation

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    name: XML Validation
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt-get install -y libxml2 libxml2-utils

      - name: Validate XML
        run: >-
            xmllint --valid --path . --noout checkstyle.xml &&
            xmllint --valid --path . --noout checkstyle-lenient.xml
